

language: python
jobs:
  include:
    - name: "Python 3.6.0 on Xenial Linux"
      python: 3.6
      env: PYTHON=3.6       # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7
      env: PYTHON=3.7        # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8
      env: PYTHON=3.8        # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: PYTHON=3.7.4
    - name: "Python 3.8 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: PYTHON=3.8
    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: PYTHON=3.6
cache:
    apt: true
    directories:
        - $HOME/.cache/pip

addons:
    apt:
        packages:
            - libhdf5-dev

install:
    #set python version
    - "pip install --upgrade pip"
    - "pip install --no-binary pyenv pyenv"
    - "export PATH=~/.pyenv/bin:$PATH"
    - "eval '$(pyenv init -)'"
    - "pyenv install --skip-existing $PYTHON"
    - "pyenv global $PYTHON"
    - "pyenv shell $PYTHON"

    # Upgrade distribution modules
    - "pip install --upgrade setuptools"
    - "pip install --upgrade pip"

    # Install build dependencies
    - "pip install wheel"
    - "pip install --trusted-host www.silx.org -r ci/requirement_travis.txt --upgrade --find-links http://www.silx.org/pub/wheelhouse"

    # Print Python info
    - "python ci/info_platform.py"
    - "pip freeze"

    # Build
    - "python setup.py build"
    - "python setup.py bdist_wheel"
    - "ls dist"

    # Install generated wheel
    - "pip install --pre --find-links dist/ --trusted-host www.silx.org --find-links http://www.silx.org/pub/wheelhouse freesas"

script:
    # Print Python info
    - "python ci/info_platform.py"
    - "pip freeze"

    # Run the tests
    - "python setup.py build test"
    - "python run_tests.py"
