os:
    - Visual Studio 2017
    - Visual Studio 2019

cache:
    - '%LOCALAPPDATA%\pip\Cache'

# fetch repository as zip archive
shallow_clone: true

environment:
    global:
        WIN_SDK_ROOT: "C:\\Program Files\\Microsoft SDKs\\Windows"

    matrix:
        # Python 3.6
        - PYTHON_DIR: "C:\\Python36-x64"

        # Python 3.7
        - PYTHON_DIR: "C:\\Python37-x64"

        # Python 3.8
        - PYTHON_DIR: "C:\\Python38-x64"

        # Python 3.9
        - PYTHON_DIR: "C:\\Python39-x64"

matrix:
  exclude:
    - os: Visual Studio 2017
      PYTHON_DIR: "C:\\Python39-x64"

install:
    - "SET PATH=%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%"

    # Install the build and runtime dependencies of the project
    - "pip install wheel"
    - "pip install --trusted-host www.edna-site.org --upgrade -r ci/requirement_appveyor.txt"

    # Print Python info
    - "python ci\\info_platform.py"
    - "pip freeze"

    # Build
    - "python setup.py build --no-openmp"
    - "python setup.py bdist_wheel bdist_msi"
    - ps: "ls dist"

    # Install the generated wheel package to test it
    - "pip install --pre --no-index --find-links dist/ freesas"
    - "pip freeze"


# Not a .NET project, build is done in the install step instead
build: false


test_script:

    #Unit tests
    - "python setup.py build test"
    - "python run_tests.py"

    #end to end tests
    - "mkdir empty"
    - "cd empty"
    - "freesas ../e2etest/e2etest_data/bsa_005_sub.dat -o test.png"
    - "auto_gpa.py.exe ../e2etest/e2etest_data/bsa_005_sub.dat"
    - "python ../e2etest/e2etest.py"

artifacts:
    # Archive the generated wheel package in the ci.appveyor.com build report.
    - path: dist\*
